# This is a basic workflow to help you get started with Actions

name: "Web Build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the web directory
on:
  push:
    paths:
      - "web/**"
    branches: [master]
  pull_request:
    paths:
      - "web/**"

defaults:
  run:
    working-directory: ./web

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
