# This is a basic workflow to help you get started with Actions

name: "Server Build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - "server/**"
    branches: [master]
  pull_request:
    paths:
      - "server/**"

defaults:
  run:
    working-directory: ./server

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
        env:
          CI: true
